"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.zeroPointPurpleCard = exports.zeroPointRedCard = exports.zeroPointGreenCard = exports.zeroPointBlueCard = exports.zeroPointColourlessCard = void 0;
const zeroPointColourlessCard = () => ({ name: 'BINARY' });
exports.zeroPointColourlessCard = zeroPointColourlessCard;
const zeroPointBlueCard = () => ({ name: 'AUTOMIMICRY (kickstarter)' });
exports.zeroPointBlueCard = zeroPointBlueCard;
const zeroPointGreenCard = () => ({ name: 'COASTAL FORMATIONS' });
exports.zeroPointGreenCard = zeroPointGreenCard;
const zeroPointRedCard = () => ({ name: 'COMET SHOWERS' });
exports.zeroPointRedCard = zeroPointRedCard;
const zeroPointPurpleCard = () => ({ name: 'ECLIPSE' });
exports.zeroPointPurpleCard = zeroPointPurpleCard;
