addBasicCard('SALIVA', 'blue', 'Classic', 1);
addBasicCard('SAUDADE', 'colourless', 'Classic', 2);
addBasicCard('SCUTES', 'blue', 'Classic', 3);
addBasicCard('SEA KINGDOMS', 'blue', 'Classic', );
addBasicCard('SELECTIVE MEMORY', 'blue', 'Classic', 0);
addBasicCard('SELF-AWARENESS', 'colourless', 'Classic', -1);
addBasicCard('SELF-REPLICATING', 'green', 'Classic', 0);
addBasicCard('SELFISH', 'purple', 'Classic', 1);
addBasicCard('SENTIENCE', 'red', 'Classic', 2);
addBasicCard('SERRATED TEETH', 'red', 'Dinolings', 5);
addBasicCard('SNEAKY', 'purple', 'Classic', 2);
addBasicCard('SOLAR FLARE', 'red', 'Classic', );
addBasicCard('SPINY', 'blue', 'Classic', 1);
addBasicCard('STICKY SECRETIONS', 'purple', 'Classic', -1);
addBasicCard('STONE SKIN', 'red', 'Classic', 2);
addBasicCard('SUBDERMAL PLATING', 'purple', 'Techlings', -1);
addBasicCard('SUPER SPREADER', 'purple', 'Classic', 2);
addBasicCard('SUPER VOLCANO', 'red', 'Classic', );
addBasicCard('SWARM (1)', 'green', 'Classic', 0);
addBasicCard('SWARM (2)', 'green', 'Classic', 0);
addBasicCard('SWARM (3)', 'green', 'Classic', 0);
addBasicCard('SWARM (4)', 'green', 'Classic', 0);
addBasicCard('SWARM (5)', 'green', 'Classic', 0);
addBasicCard('SWARM (6)', 'green', 'Classic', 0);
addBasicCard('SWEAT', 'blue', 'Classic', 2);
addBasicCard('SYMBIOSIS', 'green', 'Classic', 3);
