addBasicCard('TALONS', 'purple', 'Dinolings', 2);
addBasicCard('TECTONIC SHIFT', 'green', 'Classic', );
addBasicCard('TEETH', 'purple', 'Classic', 1);
addBasicCard('TELEKINETIC', 'purple', 'Classic', 1);
addBasicCard('TEMPORAL SANDS', 'red', 'Classic', );
addBasicCard('TENTACLES', 'blue', 'Classic', 1);
addBasicCard('TERRITORIAL', 'red', 'Classic', 1);
addBasicCard('TERROR BEAK', 'blue', 'Dinolings', 3);
addBasicCard('TETRACHROMATIC', 'purple', 'multi-colour', 4);
addBasicCard('THAGOMIZER', 'green', 'Dinolings', 1);
addBasicCard('THE BIG ONE', 'green', 'Classic', );
addBasicCard('THE BILBIES', 'colourless', 'Meaning of Life', );
addBasicCard('THE BIRTH OF LIFE', 'colourless', 'Classic', );
addBasicCard('THE CABOCHON', 'red', 'Meaning of Life', );
addBasicCard('THE COSMIC JINX', 'purple', 'Meaning of Life', );
addBasicCard('THE DANCER', 'colourless', 'Meaning of Life', );
addBasicCard('THE FELLMONGER', 'red', 'Meaning of Life', );
addBasicCard('THE FOUR HORSEMEN', 'colourless', 'Classic', );
addBasicCard('THE JELLYFISH', 'purple', 'Meaning of Life', );
addBasicCard('THE LOGICIAN', 'colourless', 'Meaning of Life', );
addBasicCard('THE LUMBERJACK', 'green', 'Meaning of Life', );
addBasicCard('THE MAGICIAN', 'colourless', 'Meaning of Life', );
addBasicCard('THE MAVEN', 'blue', 'Meaning of Life', );
addBasicCard('THE MESSIAH', 'red', 'Classic', );
addBasicCard('THE SOOTHSAYER', 'blue', 'Meaning of Life', );
addBasicCard('THE SPIRIT GARDENER', 'green', 'Meaning of Life', );
addBasicCard('THE THIRD EYE', 'colourless', 'Classic', 0);
addBasicCard('THE TIGRIS', 'red', 'Meaning of Life', );
addBasicCard('THE VAGRANT', 'red', 'Meaning of Life', );
addBasicCard('THE VIXEN', 'blue', 'Meaning of Life', );
addBasicCard('THE WARBLER', 'green', 'Meaning of Life', );
addBasicCard('THE WARRIOR', 'red', 'Meaning of Life', );
addBasicCard('THE WEAVER', 'purple', 'Meaning of Life', );
addBasicCard('TINY', 'blue', 'Classic', 17);
addBasicCard('TINY ARMS', 'red', 'Dinolings', -1);
addBasicCard('TINY LITTLE MELONS', 'green', 'Classic', 1);
addBasicCard('TRANSGENIC MODIFICATION', 'green', 'Techlings', 1);
addBasicCard('TROPICAL LANDS', 'green', 'Classic', );
addBasicCard('TRUNK', 'green', 'Classic', 1);
addBasicCard('TUBE FEET', 'blue', 'KSE', 2);
